<?php
    $title = $block->getTitle();
    $object = $block ->getInform();
    $id = $object['id'];
    $tittle = $object['title'];
    $des = $object['description'];
?>
<h2><?=$title;?></h2>
<form method="post" action="<?=$block->getSaveBase();?>" style="margin-top: 100px;">
    <fieldset style="margin: 0 auto; width: 50%">
        <div>
            <label for="id"><?= __("ID") ?></label>
            <input type="text" readonly name="id" value="<?=$id;?>" style="background-color: gray;" >
        </div>
        <div>
            <label for="title"><?= __("TITLE") ?></label>
                <input type="text" name="title" value="<?=$tittle;?>" />
        </div>
        <div>
            <label for="description"><?= __("DESCRIPTION") ?></label>
                <input type="text" name="description" value="<?=$des;?>" />
        </div>
        <input style="margin-left:50%; transform:translateX(-50%)" type="submit" name="btn"  />
    </fieldset>
</form>