<?php
$title = $block->getTitle();
$posts = $block->getAllPost();
?>
<?php if (count($posts) > 0): ?>
    <h2><?=$title;?></h2>
    <table class="abc" border="1">
        <tr>
            <th><?= __("ID") ?></th>
            <th><?= __("TITLE") ?></th>
            <th><?= __("DESCRIPTION") ?></th>
            <th><?= __("CREATE_AT") ?></th>
            <th><?= __("UPDATE_AT") ?></th>
            <th><?= __("ACTION") ?></th>
        </tr>
        <?php foreach ($posts as $post): ?>
            <tr>
                <td><?= $post->getId() ?></td>
                <td><?= $post->getTitle() ?></td>
                <td><?= $post->getDescription() ?></td>
                <td><?= $post->getCreate_at() ?></td>
                <td><?= $post->getUpdate_at() ?></td>
                <td><a href="<?= $block->getEditBase($post->getId())?>">Edit </a><a href="<?= $block->getDeleteBase($post->getId())?>">Delete</a></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
<hr />
<form method="post" action="<?= $block->getSaveBase() ?>">
    <fieldset style="margin: 0 auto; width: 50%">
       
        <div>
            <label for="title"><?= __("TITLE") ?></label>
                <input type="text" name="title"/>
        </div>
        <div>
            <label for="description"><?= __("DESCRIPTION") ?></label>
                <input type="text" name="description"/>
        </div>
        <input type="submit" style="margin-left:50%; transform:translateX(-50%)" value="<?= __("Add post") ?>" />
    </fieldset>
</form>